"""init

Revision ID: 164c2ee6d11d
Revises: 
Create Date: 2019-01-21 09:23:46.349503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164c2ee6d11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('md5_name', sa.String(length=128), nullable=True),
    sa.Column('json_name', sa.String(length=128), nullable=True),
    sa.Column('rar_name', sa.String(length=128), nullable=True),
    sa.Column('is_checked', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('backup_version', sa.String(length=64), nullable=True),
    sa.Column('producer', sa.String(length=64), nullable=True),
    sa.Column('producer_id', sa.String(length=64), nullable=True),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('em_version', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('json_name'),
    sa.UniqueConstraint('md5_name'),
    sa.UniqueConstraint('rar_name'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('register_time', sa.String(length=40), nullable=True),
    sa.Column('toggle', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('records')
    op.drop_table('fusers')
    # ### end Alembic commands ###
