"""third

Revision ID: 24eac0d245bc
Revises: dded0ca3ba5d
Create Date: 2018-11-15 20:43:19.200870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24eac0d245bc'
down_revision = 'dded0ca3ba5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'manufacturer_number',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'manufacturer_number',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
