"""user toggle

Revision ID: 4aef3cd68f93
Revises: 759e3aa37c1b
Create Date: 2019-01-07 19:09:58.245206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aef3cd68f93'
down_revision = '759e3aa37c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('toggle', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'toggle')
    # ### end Alembic commands ###
