"""test

Revision ID: 66797ad429b3
Revises: 
Create Date: 2018-12-03 12:48:31.554546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66797ad429b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mylab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mylab')
    # ### end Alembic commands ###
