"""remove test

Revision ID: 6d27e06f3a1c
Revises: 66797ad429b3
Create Date: 2018-12-03 12:55:52.730962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d27e06f3a1c'
down_revision = '66797ad429b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mylab')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mylab',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mylab_pkey')
    )
    # ### end Alembic commands ###
