"""split user

Revision ID: 759e3aa37c1b
Revises: 976f00b3f744
Create Date: 2019-01-07 19:08:31.206869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '759e3aa37c1b'
down_revision = '976f00b3f744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('corpname', table_name='users')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'corpname')
    op.drop_column('users', 'manufacturer_number')
    op.drop_column('users', 'official_web')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('official_web', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('manufacturer_number', mysql.VARCHAR(length=4), nullable=True))
    op.add_column('users', sa.Column('corpname', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('users', sa.Column('contact_number', mysql.VARCHAR(length=36), nullable=True))
    op.create_index('corpname', 'users', ['corpname'], unique=True)
    # ### end Alembic commands ###
