"""second

Revision ID: aceff5452ae3
Revises: 378ca54a6c52
Create Date: 2018-10-23 13:48:34.605793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aceff5452ae3'
down_revision = '378ca54a6c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'time')
    # ### end Alembic commands ###
