"""modify user

Revision ID: e114bf1e8f68
Revises: 6d27e06f3a1c
Create Date: 2018-12-03 15:19:33.634729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e114bf1e8f68'
down_revision = '6d27e06f3a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('contact_number', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('official_web', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'official_web')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
