"""fuser1

Revision ID: ecff47dd3336
Revises: bbdddabec438
Create Date: 2019-01-17 16:06:49.817191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecff47dd3336'
down_revision = 'bbdddabec438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fusers', 'register_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fusers', sa.Column('register_time', mysql.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
